name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MLFLOW_TRACKING_URI: sqlite:///${{ github.workspace }}/mlflow.db

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: pip install mlflow==3.11.1 scikit-learn pandas numpy
      - name: Run training
        run: mlflow run MLproject --env-manager=local --experiment-name "Latihan Credit Scoring"
      - name: Save run ID
        run: |
          RUN_ID=$(mlflow runs list --experiment-name "Latihan Credit Scoring" --order-by start_time DESC --limit 1 --output table | tail -n 1 | awk '{print $1}')
          echo "RUN_ID=$RUN_ID" > run_id.txt
      - uses: actions/upload-artifact@v3
        with:
          name: run-id
          path: run_id.txt