name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"
  # Tracking URI database berbasis SQLite (absolute path) agar parent & child run konsisten
  MLFLOW_TRACKING_URI: sqlite:///${{ github.workspace }}/mlflow.db
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode
      - uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Cek env (opsional)
      - name: Check Env
        run: echo $CSV_URL

      # 4. Install dependensi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==3.11.1 scikit-learn pandas numpy

      # 5. Bersihkan data training sebelumnya
      - name: Clean previous mlflow data
        run: |
          rm -f mlflow.db
          rm -rf mlruns

      # 6. Jalankan pelatihan model
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local --experiment-name "Credit_Score_Experiment"
      # 7. Ambil run_id terbaru dari folder mlruns (tanpa database, langsung dari path)
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # 8. Bangun Docker image menggunakan perintah MLflow build-docker
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"

      # 9. Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 10. Tag image sesuai nama Docker Hub
      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      # 11. Push image ke Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
